version: '3.8'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: practice
      MONGO_INITDB_ROOT_PASSWORD: practice
    ports:
      - "27017:27017"
    volumes:
      - .src/java/com/product/app/data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: practice
      ME_CONFIG_MONGODB_ADMINPASSWORD: practice
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_MONGODB_SERVER: mongo

networks:
  default:
    name: product_app
